const SmartPhones = [
    {
        "Id" : 0,
        "Name" : "MOTOROLA g13",
        "price" : 9999,
        "FullName" : "MOTOROLA g13 (Lavender Blue, 128 GB)  (4 GB RAM)",
        "Message" : "Get ready to experience awesomeness with an ultra-thin and unmistakably modern design. Slim, light, and premium with carefully considered and thoughtfully crafted details. Be vibrant with a design that truly stands out.",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/d/h/f/g13-pawv0028in-motorola-original-imagz4rbawxkbyjg.jpeg?q=70",
    },
    {
        "Id" : 1,
        "Name" : "realme C30",
        "price" : 5999,
        "FullName" : "realme C30 (Bamboo Green, 32 GB)  (2 GB RAM)",
        "Message" : "Explore your inner self and be outspoken about it with the realme C30 smartphone which reflects your persona to the whole world with its intuitive nature. Powered by the Unisoc T612 processor, you can seamlessly multitask and get things done at your convenience. Furthermore, an 8 MP AI-driven rear camera ",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/l4ln8nk0/mobile/p/h/p/-original-imagfggryyzyvhgw.jpeg?q=70",
    },
    {
        "Id" : 2,
        "Name" : "REDMI 10",
        "price" : 9999,
        "FullName" : "REDMI 10 (Pacific Blue, 64 GB)  (4 GB RAM)",
        "Message" : "Let go of the inhibitions and enjoy speed operation and flawless user experience with Redmi 10. This phone is powered by Snapdragon 680 processor with a savvy 6 nm architecture that makes juggling fun. This device is incorporated with 4 GB of RAM ",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/m/q/e/-original-imagk4nz6xgtexam.jpeg?q=70",
    },
    {
        "Id" : 3,
        "Name" : "REDMI A1",
        "price" : 6405,
        "FullName" : "REDMI A1 (Black, 32 GB)  (2 GB RAM)",
        "Message" : "Ideal for quick and convenient usage, the REDMI A1 Smartphone is just what you need to move fast and smartly every day with your lifestyle. Its battery capacity of up to 5000 mAh makes it convenient for you to go on for hours without worrying about interruptions.",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/6/j/g/-original-imagkjwrwzztvye6.jpeg?q=70",
    },
    {
        "Id" : 4,
        "Name" : "realme C55",
        "price" : 13999,
        "FullName" : "realme C55 (Rainy Night, 128 GB)  (8 GB RAM)",
        "Message" : "Carry a sophisticated smartphone with you that allows you to multitask effortlessly and continue working no matter how challenging the day appears to be. The 64 MP AI camera of the Realme C55 enables you to snap stunning, high-quality photographs that capture every detail with remarkable clarity. Get a fantastic visual experience as well with the 17.07 cm (6.72) 90 Hz FHD+ display, which can captivate and excite you.",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/h/y/7/-original-imagzbs5gjxey4wy.jpeg?q=70",
    },
    {
        "Id" : 5,
        "Name" : "OnePlus 10R",
        "price" : 32880,
        "FullName" : "OnePlus 10R (Forest Green, 128 GB)  (8 GB RAM)",
        "Message" : "Explore your inner self and be outspoken about it with the realme C30 smartphone which reflects your persona to the whole world with its intuitive nature. Powered by the Unisoc T612 processor, you can seamlessly multitask and get things done at your convenience. Furthermore, an 8 MP AI-driven rear camera ",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/j/b/o/-original-imageypzw8gumvyz.jpeg?q=70",
    },
    {
        "Id" : 6,
        "Name" : "OnePlus Nord 2T",
        "price" : 25999,
        "FullName" : "OnePlus Nord 2T 5G (Gray Shadow, 128 GB)  (8 GB RAM)",
        "Message" : "Combining powerful performance with a user-friendly experience, the OnePlus Nord 2T 5G Smartphone is a must-have. It boasts up to 16.33 cm (6.43) AMOLED display with a resolution of up to 1080x2400p, ensuring sharp and clear images. In addition, the screen supports HDR10+ and has a refresh rate of up to 90 Hz, providing an immersive viewing experience. ",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/f/a/v/-original-imagfx6b9shazw8u.jpeg?q=70",
    },
    {
        "Id" : 7,
        "Name" : "APPLE iPhone 14",
        "price" : 115999,
        "FullName" : "APPLE iPhone 14 (Purple, 128 GB)",
        "Message" : "Best smart phone under this price range compare to other phones in 2023 if you see overall build quality, performance and Camera with autofocus and video action mode are awesome 50% extra RAM compared",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/9/e/e/-original-imaghx9q5rvcdghy.jpeg?q=70",
    },
    {
        "Id" : 8,
        "Name" : "realme C30",
        "price" : 5999,
        "FullName" : "realme C30 (Bamboo Green, 32 GB)  (2 GB RAM)",
        "Message" : "Explore your inner self and be outspoken about it with the realme C30 smartphone which reflects your persona to the whole world with its intuitive nature. Powered by the Unisoc T612 processor, you can seamlessly multitask and get things done at your convenience. Furthermore, an 8 MP AI-driven rear camera ",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/l4ln8nk0/mobile/p/h/p/-original-imagfggryyzyvhgw.jpeg?q=70",
    },
    {
        "Id" : 9,
        "Name" : "MOTOROLA e13",
        "price" : 7999,
        "FullName" : "MOTOROLA e13 (Cosmic Black, 64 GB)  (4 GB RAM)",
        "Message" : "Explore your inner self and be outspoken about it with the realme C30 smartphone which reflects your persona to the whole world with its intuitive nature. Powered by the Unisoc T612 processor, you can seamlessly multitask and get things done at your convenience. Furthermore, an 8 MP AI-driven rear camera ",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/p/o/z/-original-imagmmmhjsjru7c2.jpeg?q=70",
    },
    {
        "Id" : 10,
        "Name" : "vivo T1 44W",
        "price" : 14499,
        "FullName" : "vivo T1 44W (Starry Sky, 128 GB)  (4 GB RAM)",
        "Message" : "Enjoy gaming thrills and capture your memorable moments with the Vivo T1 smartphone. This mobile phone is driven by a Snapdragon 680 processor so that you can get speeded up performance on this phone. Also, it comes with a 50 MP high-definition camera so that you can click sharp details even in low light conditions. And, thanks to the Funtouch OS 12, you can enjoy a smooth user experience.",
        "ImgAdd" : "https://rukminim1.flixcart.com/image/416/416/l2p23rk0/mobile/s/4/3/-original-imagdznhcbdfwfud.jpeg?q=70",
    }
]

export default SmartPhones;